# backend:
#   name: git-gateway
#   repo: codemandy/Nayamollcom
#   branch: main
#   site_domain: https://6255c19863e8ce0009647cc1--nayamoll.netlify.app/
#   publish_mode: editorial_workflow
#   auth_type: implicit
#   app_id: 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

# Backend https://www.netlifycms.org/docs/configuration-options/#backend
backend:
  name: git-gateway
  repo: codemandy/Nayamollcom
  branch: main
# Publish mode https://www.netlifycms.org/docs/configuration-options/#publish-mode
publish_mode: editorial_workflow
# Media and Public Folders https://www.netlifycms.org/docs/configuration-options/#media-and-public-folders
media_folder: 'assets/images/uploads' # Media files will be stored in the repo under images/uploads
public_folder: '/images/uploads'


collections:
  - name: 'site-settings'
    label: 'Website Settings'
    files:
      - label: 'Website settings'
        name: 'site'
        file: '_data/site.yml'
        fields:
        - { label: 'Project Title', name: 'project title', widget: 'string' }
        - { label: 'Body tekst', name: 'body tekst', widget: 'markdown' }
        - { label: 'Credits', name: 'credits', widget: 'string' }
        - label: 'Seo Tagline'
          name: 'seo tagline'
          widget: 'object'
          fields:
            - label: 'Tagline'
              name: 'tagline'
              width: 'string'



  - name: 'posts'
    label: 'Posts'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Project Title', name: 'project title', widget: 'string' }
      - { label: 'Body tekst', name: 'body tekst', widget: 'markdown' }
      - { label: 'Credits', name: 'credits', widget: 'string' }
      # - label: 'Seo Tagline', name: se
      # - { label: 'Publish Date', name: 'date', widget: 'hidden' }


  - name: 'page'
    label: 'Page'
    folder: '_pages/'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: 'Body', name: 'body', widget: 'markdown'}




  - name: 'about'
    label: 'About'
    editor:
      preview: false
    files:
      - label: 'About Page'
        name: 'about'
        file: 'about.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'hidden', default: 'about' }
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'about' }
          - { label: 'Body', name: 'body', widget: 'markdown' }


  # collections:
  # - name: "blog" # Used in routes, e.g., /admin/collections/blog
  #   label: "Blog" # Used in the UI
  #   folder: "_posts/blog" # The path to the folder where the documents are stored
  #   create: true # Allow users to create new documents in this collection
  #   slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  #   fields: # The fields for each document, usually in front matter
  #     - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
  #     - {label: "Title", name: "title", widget: "string"}
  #     - {label: "Publish Date", name: "date", widget: "datetime"}
  #     - {label: "Featured Image", name: "thumbnail", widget: "image"}
  #     - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
  #     - {label: "Body", name: "body", widget: "markdown"}

# collections:
#   - name: "post" # Used in routes, e.g. /admin/collections/blog
#     label: "Post" # Used in the UI
#     folder: "_posts" # The path to the folder where the documents are stored
#     create: true # Allow users to create new documents in this collection
#     slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
#     fields: # The fields for each document, usually in front matter
#       - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
#       - {label: "Title", name: "title", widget: "string"}
#       - {label: "Body", name: "body", widget: "markdown"}
